<?php

/**
 * @file
 * Contains quiz.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function quiz_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the quiz module.
    case 'help.page.quiz':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A module that enables the creation of quizzes.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function quiz_theme() {
  $theme = array(
    'quiz_list_questions' => array(
      'variables' => array(
        'content' => NULL,
        'questions' => NULL,
      ),
      'template' => 'listQuestions'
    ),

    'quiz_list_results' => array(
      'variables' => array(
        'markup' => NULL,
      ),
      'template' => 'listResults'
    ),

    'question' => array(
      'variables' => array(
        'content' => NULL,
      )
    )
  );

  return $theme;
}

/**
 * Implements hook_uninstall().
 */
function quiz_uninstall() {

}

/**
 * Implements hook_toolbar().
 */
function quiz_toolbar() {
  $links['add_quiz'] = array(
    'title' => t('Add Quiz'),
    'url' => Url::fromRoute('entity.quiz.add_form_simple'),
    'options' => array(
      'title' => t('Add Quiz'),
    ),
  );

  $links['list_quiz'] = array(
    'title' => t('List Quizzes'),
    'url' => Url::fromRoute('entity.quiz.collection'),
    'options' => array(
      'title' => t('List Quizzes'),
    ),
  );

  $items['quiz'] = array(
    '#type' => 'toolbar_item',
    'tab' => array(
      '#type' => 'link',
      '#title' => t('Quiz'),
      '#url' => Url::fromRoute('<front>'),
      '#attributes' => array(
        'title' => t('Quizzes'),
      ),
    ),
    'tray' => array(
      '#heading' => t('Quiz'),
      'shortcuts' => array(
        '#theme' => 'links__toolbar_example',
        '#links' => $links,
        '#attributes' => array(
          'class' => array('toolbar-menu'),
        ),
      ),
    )
  );

  return $items;
}